name: Python Script Workflow

on:
  push: # This triggers the workflow on push to any branch
  schedule:
    - cron: '0 0 * * *'  # This schedules the workflow to run at midnight every day
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v2  # This sets up Python
      with:
        python-version: 3.8  # You can specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt  # Install any required packages

    - name: Set up environment variables
      run: |
        echo "NOTION_API_TOKEN=${{ secrets.NOTION_API_TOKEN }}" >> $GITHUB_ENV
        echo "TASK_DATABASE_ID=${{ secrets.TASK_DATABASE_ID }}" >> $GITHUB_ENV
        echo "NOTEBOOK_DATABASE_ID=${{ secrets.NOTEBOOK_DATABASE_ID }}" >> $GITHUB_ENV
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        TASK_DATABASE_ID: ${{ secrets.TASK_DATABASE_ID }}
        NOTEBOOK_DATABASE_ID: ${{ secrets.NOTEBOOK_DATABASE_ID }}
        
    - name: Run Python script
      run: python notion_script.py  # Use 'notion_script.py' as the script name
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        TASK_DATABASE_ID: ${{ secrets.TASK_DATABASE_ID }}
        NOTEBOOK_DATABASE_ID: ${{ secrets.NOTEBOOK_DATABASE_ID }}
